/* ============================================================================
   Serie A Scout Index — assistente AI
   ----------------------------------------------------------------------------
   Widget self-contained: si aggancia da solo al <body>, porta i suoi stili e il
   suo dizionario IT/EN. Non ha dipendenze; se i18n.js c'e' segue la lingua
   scelta li', altrimenti parte in italiano.

   La chiave API non e' qui e non e' in nessuna pagina: il widget parla solo con
   il Worker Cloudflare (vedi worker/README.md).
   ========================================================================== */

(function () {
  "use strict";

  /* --- CONFIGURAZIONE -----------------------------------------------------
     Sostituisci con l'URL che stampa `wrangler deploy`.
     Finche' resta il placeholder, il widget non si monta. */
  const WORKER_URL = "https://serie-a-scout-ai.CAMBIAMI.workers.dev";
  /* ---------------------------------------------------------------------- */

  const MAX_TURNS = 16;
  const MAX_CHARS = 1500;

  if (WORKER_URL.indexOf("CAMBIAMI") !== -1) {
    console.warn("[ai_chat] WORKER_URL non configurato: assistente disattivato.");
    return;
  }

  /* ------------------------------------------------------------------ */
  /* Stringhe                                                            */
  /* ------------------------------------------------------------------ */

  const STRINGS = {
    it: {
      fab: "Chiedi al modello",
      title: "Assistente Scout Index",
      subtitle: "Domande sui dati e sul modello",
      close: "Chiudi",
      placeholder: "Chiedi qualcosa sui giocatori o sul modello…",
      send: "Invia",
      clear: "Nuova conversazione",
      empty:
        "Rispondo con i numeri del modello: TPI, z-score per dimensione, contesti, forma, età. Non invento dati che non ci sono.",
      disclaimer:
        "Risposte generate da un modello linguistico sui dati del progetto. Verifica sempre i numeri sulla dashboard.",
      suggestions: [
        "Chi è il miglior under-23 secondo il modello?",
        "Perché Lautaro è primo nel TPI?",
        "Confronta i primi due centrocampisti",
        "Cosa misura la centralità offensiva?",
        "Chi rende meglio contro le difese forti?",
      ],
      thinking: "Sto leggendo i dati…",
      err_rate: "Troppe domande ravvicinate. Riprova fra un minuto.",
      err_quota: "Limite giornaliero della demo raggiunto. Riprova domani.",
      err_net: "Non riesco a raggiungere l'assistente. Riprova fra poco.",
      err_generic: "Qualcosa è andato storto. Riprova.",
      err_refusal: "Non posso rispondere a questa domanda.",
      truncated: "(risposta troncata)",
    },
    en: {
      fab: "Ask the model",
      title: "Scout Index Assistant",
      subtitle: "Questions about the data and the model",
      close: "Close",
      placeholder: "Ask about players or about the model…",
      send: "Send",
      clear: "New conversation",
      empty:
        "I answer with the model's own numbers: TPI, per-dimension z-scores, contexts, form, age. I won't make up data that isn't there.",
      disclaimer:
        "Answers generated by a language model over this project's data. Always check the numbers on the dashboard.",
      suggestions: [
        "Who is the best under-23 according to the model?",
        "Why is Lautaro first in TPI?",
        "Compare the top two midfielders",
        "What does offensive centrality measure?",
        "Who performs best against strong defences?",
      ],
      thinking: "Reading the data…",
      err_rate: "Too many questions in a row. Try again in a minute.",
      err_quota: "Daily demo limit reached. Try again tomorrow.",
      err_net: "Can't reach the assistant. Try again shortly.",
      err_generic: "Something went wrong. Try again.",
      err_refusal: "I can't answer that.",
      truncated: "(response truncated)",
    },
  };

  function lang() {
    try {
      if (window.SerieAi18n && window.SerieAi18n.getLang) {
        return window.SerieAi18n.getLang() === "en" ? "en" : "it";
      }
      return localStorage.getItem("lang") === "en" ? "en" : "it";
    } catch (e) {
      return "it";
    }
  }

  function s(key) {
    return STRINGS[lang()][key];
  }

  /* ------------------------------------------------------------------ */
  /* Stili                                                               */
  /* ------------------------------------------------------------------ */

  const CSS = `
.aic-fab{position:fixed;right:20px;bottom:20px;z-index:9000;
  display:flex;align-items:center;gap:8px;padding:12px 18px;border:none;
  border-radius:26px;cursor:pointer;font:600 14px/1 -apple-system,BlinkMacSystemFont,"SF Pro Display","Helvetica Neue",sans-serif;
  color:#fff;background:linear-gradient(135deg,#0a84ff,#5e5ce6);
  box-shadow:0 8px 28px rgba(10,132,255,.38);
  transition:transform .18s ease,box-shadow .18s ease}
.aic-fab:hover{transform:translateY(-2px);box-shadow:0 12px 34px rgba(10,132,255,.5)}
.aic-fab[hidden]{display:none}
.aic-fab-icon{font-size:16px;line-height:1}

.aic-panel{position:fixed;right:20px;bottom:20px;z-index:9001;
  width:min(420px,calc(100vw - 32px));height:min(560px,calc(100vh - 40px));
  display:flex;flex-direction:column;overflow:hidden;
  border-radius:20px;border:1px solid rgba(255,255,255,.16);
  background:rgba(22,22,26,.86);
  backdrop-filter:saturate(180%) blur(30px);-webkit-backdrop-filter:saturate(180%) blur(30px);
  box-shadow:0 24px 70px rgba(0,0,0,.6);
  font:14px/1.55 -apple-system,BlinkMacSystemFont,"SF Pro Display","Helvetica Neue",sans-serif;
  color:#fff;
  opacity:0;transform:translateY(12px) scale(.98);pointer-events:none;
  transition:opacity .2s ease,transform .2s ease}
.aic-panel.aic-open{opacity:1;transform:none;pointer-events:auto}

.aic-head{display:flex;align-items:center;gap:10px;padding:14px 16px;
  border-bottom:1px solid rgba(255,255,255,.1);flex-shrink:0}
.aic-dot{width:8px;height:8px;border-radius:50%;background:#30d158;
  box-shadow:0 0 8px rgba(48,209,88,.7);flex-shrink:0}
.aic-titles{flex:1;min-width:0}
.aic-title{font-size:14px;font-weight:700;letter-spacing:-.2px}
.aic-sub{font-size:11px;color:rgba(235,235,245,.5);margin-top:1px}
.aic-iconbtn{background:none;border:none;cursor:pointer;padding:5px 8px;border-radius:8px;
  color:rgba(235,235,245,.55);font-size:16px;line-height:1;transition:background .15s,color .15s}
.aic-iconbtn:hover{background:rgba(255,255,255,.08);color:#fff}

.aic-log{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:14px;
  scrollbar-width:thin;scrollbar-color:rgba(255,255,255,.2) transparent}
.aic-log::-webkit-scrollbar{width:6px}
.aic-log::-webkit-scrollbar-thumb{background:rgba(255,255,255,.18);border-radius:3px}

.aic-empty{color:rgba(235,235,245,.6);font-size:13px;line-height:1.6}
.aic-chips{display:flex;flex-wrap:wrap;gap:7px;margin-top:14px}
.aic-chip{padding:7px 12px;border-radius:14px;cursor:pointer;text-align:left;
  border:1px solid rgba(10,132,255,.28);background:rgba(10,132,255,.09);
  color:#7ab8ff;font:500 12px/1.35 inherit;transition:background .15s,border-color .15s}
.aic-chip:hover{background:rgba(10,132,255,.18);border-color:rgba(10,132,255,.5)}

.aic-msg{max-width:92%;font-size:13.5px}
.aic-msg.u{align-self:flex-end;max-width:85%;padding:9px 13px;border-radius:15px 15px 4px 15px;
  background:rgba(10,132,255,.9);color:#fff;white-space:pre-wrap;word-break:break-word}
.aic-msg.a{align-self:flex-start;color:rgba(235,235,245,.92);word-break:break-word}
.aic-msg.a strong{color:#fff;font-weight:650}
.aic-msg.a code{font-family:"SF Mono","Cascadia Code",monospace;font-size:12.5px;
  background:rgba(255,255,255,.09);padding:1px 5px;border-radius:4px}
.aic-msg.a ul{margin:6px 0;padding-left:18px}
.aic-msg.a li{margin:3px 0}
.aic-msg.a p{margin:0 0 8px}
.aic-msg.a p:last-child{margin-bottom:0}
.aic-msg.err{align-self:flex-start;color:#ff8378;font-size:13px}

.aic-cursor{display:inline-block;width:7px;height:14px;vertical-align:-2px;
  background:rgba(10,132,255,.85);border-radius:1px;animation:aic-blink 1s steps(2) infinite}
@keyframes aic-blink{50%{opacity:0}}

.aic-foot{flex-shrink:0;padding:10px 12px 12px;border-top:1px solid rgba(255,255,255,.1)}
.aic-inputrow{display:flex;gap:8px;align-items:flex-end}
.aic-input{flex:1;resize:none;max-height:110px;padding:10px 12px;
  border-radius:12px;border:1px solid rgba(255,255,255,.14);
  background:rgba(255,255,255,.06);color:#fff;
  font:13.5px/1.45 inherit;outline:none;transition:border-color .15s}
.aic-input:focus{border-color:rgba(10,132,255,.6)}
.aic-input::placeholder{color:rgba(235,235,245,.35)}
.aic-send{flex-shrink:0;width:36px;height:36px;border:none;border-radius:11px;cursor:pointer;
  background:#0a84ff;color:#fff;font-size:15px;line-height:1;transition:opacity .15s,background .15s}
.aic-send:hover:not(:disabled){background:#3b9bff}
.aic-send:disabled{opacity:.35;cursor:default}
.aic-note{margin-top:8px;font-size:10.5px;line-height:1.4;color:rgba(235,235,245,.33)}

@media (max-width:520px){
  .aic-panel{right:8px;left:8px;bottom:8px;width:auto;height:calc(100vh - 16px);border-radius:16px}
  .aic-fab{right:12px;bottom:12px;padding:11px 15px}
}
@media (prefers-reduced-motion:reduce){
  .aic-fab,.aic-panel{transition:none}
  .aic-cursor{animation:none}
}`;

  /* ------------------------------------------------------------------ */
  /* Rendering testo                                                     */
  /* ------------------------------------------------------------------ */

  function esc(str) {
    return str
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
  }

  // Markdown minimo. L'escape viene PRIMA di qualunque sostituzione, quindi
  // niente HTML del modello puo' finire nel DOM.
  function render(text) {
    let html = esc(text);
    html = html.replace(/`([^`\n]+)`/g, "<code>$1</code>");
    html = html.replace(/\*\*([^*\n]+)\*\*/g, "<strong>$1</strong>");

    const blocks = html.split(/\n{2,}/);
    return blocks
      .map(function (block) {
        const lines = block.split("\n");
        const isList = lines.every(function (l) {
          return /^\s*[-*]\s+/.test(l) || l.trim() === "";
        });
        if (isList && lines.some((l) => l.trim())) {
          const items = lines
            .filter((l) => l.trim())
            .map((l) => "<li>" + l.replace(/^\s*[-*]\s+/, "") + "</li>")
            .join("");
          return "<ul>" + items + "</ul>";
        }
        return "<p>" + lines.join("<br>") + "</p>";
      })
      .join("");
  }

  /* ------------------------------------------------------------------ */
  /* Widget                                                              */
  /* ------------------------------------------------------------------ */

  let history = [];
  let busy = false;
  let el = {};

  function build() {
    const style = document.createElement("style");
    style.textContent = CSS;
    document.head.appendChild(style);

    const fab = document.createElement("button");
    fab.className = "aic-fab";
    fab.type = "button";
    fab.innerHTML = '<span class="aic-fab-icon">&#10024;</span><span class="aic-fab-label"></span>';

    const panel = document.createElement("div");
    panel.className = "aic-panel";
    panel.setAttribute("role", "dialog");
    panel.setAttribute("aria-modal", "false");
    panel.innerHTML =
      '<div class="aic-head">' +
      '<span class="aic-dot"></span>' +
      '<div class="aic-titles"><div class="aic-title"></div><div class="aic-sub"></div></div>' +
      '<button type="button" class="aic-iconbtn aic-clear">&#8635;</button>' +
      '<button type="button" class="aic-iconbtn aic-close">&#10005;</button>' +
      "</div>" +
      '<div class="aic-log"></div>' +
      '<div class="aic-foot">' +
      '<div class="aic-inputrow">' +
      '<textarea class="aic-input" rows="1" maxlength="' + MAX_CHARS + '"></textarea>' +
      '<button type="button" class="aic-send">&#8593;</button>' +
      "</div>" +
      '<div class="aic-note"></div>' +
      "</div>";

    document.body.appendChild(fab);
    document.body.appendChild(panel);

    el = {
      fab: fab,
      fabLabel: fab.querySelector(".aic-fab-label"),
      panel: panel,
      title: panel.querySelector(".aic-title"),
      sub: panel.querySelector(".aic-sub"),
      log: panel.querySelector(".aic-log"),
      input: panel.querySelector(".aic-input"),
      send: panel.querySelector(".aic-send"),
      note: panel.querySelector(".aic-note"),
      clear: panel.querySelector(".aic-clear"),
      close: panel.querySelector(".aic-close"),
    };

    el.send.disabled = true;

    fab.addEventListener("click", open);
    el.close.addEventListener("click", close);
    el.clear.addEventListener("click", reset);
    el.send.addEventListener("click", submit);

    el.input.addEventListener("keydown", function (e) {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        submit();
      }
    });
    el.input.addEventListener("input", function () {
      el.input.style.height = "auto";
      el.input.style.height = Math.min(el.input.scrollHeight, 110) + "px";
      el.send.disabled = busy || el.input.value.trim() === "";
    });

    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape" && el.panel.classList.contains("aic-open")) close();
    });

    document.addEventListener("i18n:changed", applyLang);
    applyLang();
  }

  function applyLang() {
    el.fabLabel.textContent = s("fab");
    el.title.textContent = s("title");
    el.sub.textContent = s("subtitle");
    el.input.placeholder = s("placeholder");
    el.note.textContent = s("disclaimer");
    el.close.title = s("close");
    el.clear.title = s("clear");
    el.send.title = s("send");
    if (history.length === 0) showEmpty();
  }

  function open() {
    el.panel.classList.add("aic-open");
    el.fab.hidden = true;
    el.input.focus();
  }

  function close() {
    el.panel.classList.remove("aic-open");
    el.fab.hidden = false;
  }

  function reset() {
    history = [];
    showEmpty();
    el.input.focus();
  }

  function showEmpty() {
    el.log.innerHTML = "";
    const box = document.createElement("div");
    box.className = "aic-empty";
    box.textContent = s("empty");

    const chips = document.createElement("div");
    chips.className = "aic-chips";
    s("suggestions").forEach(function (q) {
      const chip = document.createElement("button");
      chip.type = "button";
      chip.className = "aic-chip";
      chip.textContent = q;
      chip.addEventListener("click", function () {
        el.input.value = q;
        submit();
      });
      chips.appendChild(chip);
    });

    box.appendChild(chips);
    el.log.appendChild(box);
  }

  function addMsg(role, text) {
    const div = document.createElement("div");
    div.className = "aic-msg " + role;
    if (role === "u") div.textContent = text;
    else div.innerHTML = render(text || "");
    el.log.appendChild(div);
    scroll();
    return div;
  }

  function addError(key) {
    const div = document.createElement("div");
    div.className = "aic-msg err";
    div.textContent = s(key);
    el.log.appendChild(div);
    scroll();
  }

  function scroll() {
    el.log.scrollTop = el.log.scrollHeight;
  }

  function setBusy(state) {
    busy = state;
    el.input.disabled = state;
    el.send.disabled = state || el.input.value.trim() === "";
  }

  /* ------------------------------------------------------------------ */
  /* Richiesta                                                           */
  /* ------------------------------------------------------------------ */

  async function submit() {
    const question = el.input.value.trim();
    if (!question || busy) return;

    if (history.length === 0) el.log.innerHTML = "";
    el.input.value = "";
    el.input.style.height = "auto";

    addMsg("u", question);
    history.push({ role: "user", content: question.slice(0, MAX_CHARS) });

    // Il Worker rifiuta oltre MAX_TURNS: tagliamo qui la coda piu' vecchia,
    // tenendo l'inizio su un turno "user" come vuole l'API.
    while (history.length > MAX_TURNS) history.splice(0, 2);

    setBusy(true);
    const bubble = addMsg("a", "");
    bubble.innerHTML = '<span class="aic-cursor"></span>';

    let answer = "";
    let failed = false;

    try {
      const res = await fetch(WORKER_URL + "/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ messages: history, lang: lang() }),
      });

      if (!res.ok) {
        bubble.remove();
        let payload = {};
        try {
          payload = await res.json();
        } catch (e) {}
        if (res.status === 429) {
          addError(payload.error === "daily_quota" ? "err_quota" : "err_rate");
        } else {
          addError("err_generic");
        }
        history.pop();
        setBusy(false);
        return;
      }

      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      while (true) {
        const chunk = await reader.read();
        if (chunk.done) break;
        buffer += decoder.decode(chunk.value, { stream: true });

        const parts = buffer.split("\n\n");
        buffer = parts.pop();

        for (const part of parts) {
          const line = part.trim();
          if (!line.startsWith("data:")) continue;
          let ev;
          try {
            ev = JSON.parse(line.slice(5).trim());
          } catch (e) {
            continue;
          }

          if (ev.type === "text") {
            answer += ev.text;
            bubble.innerHTML = render(answer) + '<span class="aic-cursor"></span>';
            scroll();
          } else if (ev.type === "done") {
            bubble.innerHTML = render(answer + (ev.truncated ? "\n\n" + s("truncated") : ""));
          } else if (ev.type === "refusal") {
            bubble.remove();
            addError("err_refusal");
            failed = true;
          } else if (ev.type === "error") {
            bubble.remove();
            addError("err_generic");
            failed = true;
          }
        }
      }
    } catch (e) {
      console.error("[ai_chat]", e);
      bubble.remove();
      addError("err_net");
      failed = true;
    }

    if (failed || !answer) {
      // Niente risposta valida: la domanda esce dalla storia, cosi' un retry
      // non riparte da una conversazione monca.
      history.pop();
    } else {
      bubble.innerHTML = render(answer);
      history.push({ role: "assistant", content: answer });
    }

    setBusy(false);
    scroll();
    el.input.focus();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", build);
  } else {
    build();
  }
})();
